AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  destinationbucket:
    Type: String

  TrailName:
    Type: String
    Default: "CloudtrailExport"

  Prefix:
    Type: String
    Default: "Prefix"

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      S3BucketName: !Ref destinationbucket
      S3KeyPrefix: !Ref Prefix
      TrailName: !Ref TrailName
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
